--DROP DATABASE
DROP DATABASE IF EXISTS Library;

--DROP TABLES

DROP TABLE IF EXISTS School_Book;
DROP TABLE IF EXISTS Book_Author;
DROP TABLE IF EXISTS Book_Category;
DROP TABLE IF EXISTS Book_Keyword;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Borrowing;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Keyword;
DROP TABLE IF EXISTS User_Registration;
DROP TABLE IF EXISTS Operator_Registration;
DROP TABLE IF EXISTS Pending_Review;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS Operator;





